- name: Check arguments
  fail: msg="{{ item }} is not defined"
  when: '{{ item }} is undefined'
  with_items:
    - dibcreate_destination
    - dibcreate_elements
    - dibcreate_env_vars
    - dibcreate_extra_packages
    - dibcreate_output_types
    - dibcreate_overwrite_dest
    - dibcreate_log_dest
  tags: [config-check]

- name: Stat destination
  stat: path={{ dibcreate_destination }}
  register: _dib_dest

- name: Build disk image
  become: true
  become_user: root
  environment: '{{ dibcreate_env_vars }}'
  shell: 'disk-image-create -n -t {{ dibcreate_output_types | join(",") }} -p {{ dibcreate_extra_packages | join(",") }} -o {{ dibcreate_destination }} {{ dibcreate_elements | join(" ") }}  2>&1 | tee {{ dibcreate_log_dest }}'
  when: dibcreate_overwrite_dest and _dib_dest.stat.exists
